/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View;
import entities.Categorie;
import entities.Chambre;
import java.awt.Color;
import java.awt.Font;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import service.CategorieService;
import service.ChambreService;
import service.ClientService;

/**
 *
 * @author golde
 */
public class ChambrePanel extends javax.swing.JPanel {
    private CategorieService cates;
     private ChambreService chs;
    private DefaultTableModel model;
    private static int id;
    /**
     * Creates new form ChambreForm
     */
    public ChambrePanel() {
        initComponents();
        chs=new ChambreService();
        cates=new CategorieService();
        model=(DefaultTableModel) jTable1.getModel();  
        afficherChambre();
        afficherCategorie();
    }

    public void afficherChambre(){
        model.setRowCount(0);
        
        for(Chambre ch:chs.findAll()){
            model.addRow(new Object[]{
                ch.getId(),
                ch.getTelephone(),
                ch.getCateg(),
                
            });
        }
    }
    
    public void afficherCategorie(){
        for(Categorie cat:cates.findAll()){
            jComboBox1.addItem(cat);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
                       

    private void ModifierChambre(java.awt.event.ActionEvent evt) {                                 
       String telephone=jTextField1.getText();
       Categorie cate=(Categorie) jComboBox1.getSelectedItem();
       Chambre ch=chs.findById(id);
       ch.setTelephone(telephone);
       ch.setCateg(cate);
       int rep=JOptionPane.showConfirmDialog(this, "Voulez vous vraiment modifier cette chambre");
                   if(rep==JOptionPane.YES_OPTION){
                       if(chs.update(ch)){
                           JOptionPane.showMessageDialog(this, "Chambre bien modifié");
                           afficherChambre();
                       }
                   }
    }                                

   
    private void ajouterChambre(java.awt.event.ActionEvent evt) {                                
        String telephone=jTextField1.getText();
       Categorie cate=(Categorie) jComboBox1.getSelectedItem();
       Chambre ch=new Chambre(telephone,cate);
       int rep=JOptionPane.showConfirmDialog(this, "Voulez vous vraiment ajouter cette chambre");
                   if(rep==JOptionPane.YES_OPTION){
                       if(chs.create(ch)){
                           JOptionPane.showMessageDialog(this, "Chambre bien ajouté");
                           afficherChambre();
                       }
                   }
    }                               

    private void supprimerChambre(java.awt.event.ActionEvent evt) {                                  
        Chambre ch=chs.findById(id);
        int rep=JOptionPane.showConfirmDialog(this, "Voulez vous vraiment supprimer ce client");
                   if(rep==JOptionPane.YES_OPTION){
                       if(chs.delete(ch)){
                           JOptionPane.showMessageDialog(this, "Client bien supprimé");
                           afficherChambre();
                       }
                      
                   }
    }                                 
    // TODO add your handling code here:


    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jComboBox1 = jComboBox1 = new JComboBox<>();
        jComboBox1.setFont(new Font("Arial", Font.PLAIN, 14));
        jComboBox1.setBackground(Color.WHITE);
        jComboBox1.setForeground(Color.BLACK);
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setBackground(new java.awt.Color(255, 255, 255));

        jButton1.setBackground(new java.awt.Color(0, 102, 255));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("modifier");
        jButton1.setBorder(null);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ModifierChambre(evt);
            }
        });

        jLabel1.setText("Telephone ");

        jLabel3.setText("Categorie ");

        jComboBox1.setBorder(null);
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(0, 102, 255));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("ajouter");
        jButton2.setBorder(null);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ajouterChambre(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(0, 102, 255));
        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("supprimer");
        jButton3.setBorder(null);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3supprimerChambre(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "id", "telephone", "Categorie"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 520, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(91, 91, 91)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE))
                .addGap(125, 125, 125))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addGap(4, 4, 4)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(74, 74, 74)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(67, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ModifierChambre(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ModifierChambre
        String telephone=jTextField1.getText();
        Categorie cate=(Categorie) jComboBox1.getSelectedItem();
        Chambre ch=chs.findById(id);
        ch.setTelephone(telephone);
        ch.setCateg(cate);
        int rep=JOptionPane.showConfirmDialog(this, "Voulez vous vraiment modifier cette chambre");
        if(rep==JOptionPane.YES_OPTION){
            if(chs.update(ch)){
                JOptionPane.showMessageDialog(this, "Chambre bien modifié");
                afficherChambre();
            }
        }
    }//GEN-LAST:event_jButton1ModifierChambre

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButton2ajouterChambre(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ajouterChambre
        String telephone=jTextField1.getText();
        Categorie cate=(Categorie) jComboBox1.getSelectedItem();
        Chambre ch=new Chambre(telephone,cate);
        int rep=JOptionPane.showConfirmDialog(this, "Voulez vous vraiment ajouter cette chambre");
        if(rep==JOptionPane.YES_OPTION){
            if(chs.create(ch)){
                JOptionPane.showMessageDialog(this, "Chambre bien ajouté");
                afficherChambre();
            }
        }
    }//GEN-LAST:event_jButton2ajouterChambre

    private void jButton3supprimerChambre(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3supprimerChambre
        Chambre ch=chs.findById(id);
        int rep=JOptionPane.showConfirmDialog(this, "Voulez vous vraiment supprimer ce client");
        if(rep==JOptionPane.YES_OPTION){
            if(chs.delete(ch)){
                JOptionPane.showMessageDialog(this, "Client bien supprimé");
                afficherChambre();
            }

        }
    }//GEN-LAST:event_jButton3supprimerChambre

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        id=Integer.parseInt(model.getValueAt(jTable1.getSelectedRow(), 0).toString());
        jTextField1.setText((String) model.getValueAt(jTable1.getSelectedRow(), 1));
        jComboBox1.setSelectedItem((Categorie) model.getValueAt(jTable1.getSelectedRow(), 2));

    }//GEN-LAST:event_jTable1MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<Categorie> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables

    
}
