/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View;

import java.text.SimpleDateFormat;
import entities.Categorie;
import entities.Chambre;
import entities.Client;
import entities.Reservation;
import java.text.ParseException;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import service.CategorieService;
import service.ChambreService;
import service.ClientService;
import service.ReservationService;
import com.itextpdf.text.pdf.PdfWriter;
import java.io.FileOutputStream;
import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.FontFactory;
import com.itextpdf.text.Paragraph;
import java.awt.Color;
import java.awt.Font;
import java.io.FileNotFoundException;
import java.util.List;
import javax.swing.JComboBox;

/**
 *
 * @author golde
 */
public class ReservationPanel extends javax.swing.JPanel {
     private ReservationService res;
    private ChambreService chserv;
    private ClientService cltserv;
    private DefaultTableModel model;
    private static int id;
    private Date date;
    private Object client;
    /**
     * Creates new form ResrvationForm
     */
    public ReservationPanel() {
        initComponents();
        res=new ReservationService();
        res=new ReservationService();
        cltserv=new ClientService();
        chserv=new ChambreService();
        model=(DefaultTableModel) jTable1.getModel();  
        afficherReservation();
        afficherChambre();
        afficherClient();
    }
       public void afficherReservation(){
           model.setRowCount(0);
        
        for(Reservation r:res.findAll()){
            model.addRow(new Object[]{
                r.getId(),
                r.getDateDebut(),
                r.getDateFin(),
                r.getCh().getCateg().getLibelle(),
                r.getClt().toString(),
                
            });
        }
       }
       
       public void afficherChambre(){
           for(Chambre ch: chserv.findAll()){
               jComboBox2.addItem(ch);
           }
       }
       public void afficherClient(){
           for(Client clt: cltserv.findAll()){
             jComboBox1.addItem(clt);
           }
       }
    /**
     * Creates new form ReservationPanel
     */
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jDateChooser2 = new com.toedter.calendar.JDateChooser();
        jComboBox1 = jComboBox1 = new JComboBox<>();
        jComboBox1.setFont(new Font("Arial", Font.PLAIN, 14));
        jComboBox1.setBackground(Color.WHITE);
        jComboBox1.setForeground(Color.BLACK);
        jComboBox2 = new JComboBox<>();
        jComboBox2.setFont(new Font("Arial", Font.PLAIN, 14));
        jComboBox2.setBackground(Color.WHITE);
        jComboBox2.setForeground(Color.BLACK);
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Date Deb", "Date Fin", "Chambre", "Client"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 555, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(69, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(87, 87, 87))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jDateChooser1.setBackground(new java.awt.Color(255, 255, 255));
        jDateChooser1.setDateFormatString("yyyy-MM-dd");

        jDateChooser2.setBackground(new java.awt.Color(255, 255, 255));
        jDateChooser2.setDateFormatString("yyyy-MM-dd");

        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });

        jLabel1.setText("Date Debut ");

        jLabel2.setText("Date Fin ");

        jLabel3.setText("Client ");

        jLabel4.setText("Chambre");

        jButton1.setBackground(new java.awt.Color(0, 102, 255));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Ajouter");
        jButton1.setBorder(null);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ajouterReservation(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(0, 102, 255));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("modifier");
        jButton2.setBorder(null);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2modifierReservation(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(0, 102, 255));
        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("supprimer");
        jButton3.setBorder(null);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3supprimerReservation(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(0, 102, 255));
        jButton4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("imprimer");
        jButton4.setBorder(null);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4imprimer(evt);
            }
        });

        jButton5.setBackground(new java.awt.Color(0, 102, 255));
        jButton5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("filtrer");
        jButton5.setBorder(null);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(134, 134, 134)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jDateChooser2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jDateChooser1, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE))
                            .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 150, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(105, 105, 105))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jDateChooser2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(7, 7, 7)
                        .addComponent(jLabel3)
                        .addGap(2, 2, 2)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(42, 42, 42)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(83, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(64, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked

        id=Integer.parseInt(model.getValueAt(jTable1.getSelectedRow(), 0).toString());
        /*jComboBox1.setSelectedItem((Client) model.getValueAt(jTable1.getSelectedRow(), 3));
        jComboBox2.setSelectedItem((Chambre) model.getValueAt(jTable1.getSelectedRow(), 4));*/
    }//GEN-LAST:event_jTable1MouseClicked

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void jButton1ajouterReservation(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ajouterReservation

        Date dateDebut =jDateChooser1.getDate();
        Date dateFin=jDateChooser2.getDate();
        Chambre ch=(Chambre) jComboBox2.getSelectedItem();
        Client clt=(Client) jComboBox1.getSelectedItem();
        Reservation reservation=new Reservation(dateDebut,dateFin,clt,ch);
        int rep=JOptionPane.showConfirmDialog(this, "Voulez vous vraiment ajouter cette reservation");
        if(rep==JOptionPane.YES_OPTION){
            if(dateDebut.after(new Date()) && dateFin.after(dateDebut)){
            if(res.create(reservation)){
                JOptionPane.showMessageDialog(this, "reservation bien ajouté");
                afficherReservation();
            }}
            else{
                JOptionPane.showMessageDialog(this, "Dates non valide");
            }
        }
    }//GEN-LAST:event_jButton1ajouterReservation

    private void jButton2modifierReservation(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2modifierReservation
        Date dateDebut =jDateChooser1.getDate();
        Date dateFin=jDateChooser2.getDate();
        Chambre ch=(Chambre) jComboBox2.getSelectedItem();
        Client clt=(Client) jComboBox1.getSelectedItem();
        Reservation reservation=res.findById(id);
        reservation.setDateDebut(dateDebut);
        reservation.setDateFin(dateFin);
        reservation.setCh(ch);
        reservation.setClt(clt);
        int rep=JOptionPane.showConfirmDialog(this, "Voulez vous vraiment modifier cette réservation");
        if(rep==JOptionPane.YES_OPTION){
            if(dateDebut.after(new Date()) && dateFin.after(dateDebut)){
            if(res.update(reservation)){
                JOptionPane.showMessageDialog(this, "réservation bien modifiée");
                afficherReservation();
            }}
            else{
                JOptionPane.showMessageDialog(this, "Dates non valide");
            }
        }
    }//GEN-LAST:event_jButton2modifierReservation

    private void jButton3supprimerReservation(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3supprimerReservation
        Reservation reservation=res.findById(id);
        int rep=JOptionPane.showConfirmDialog(this, "Voulez vous vraiment supprimer cette réservation");
        if(rep==JOptionPane.YES_OPTION){
            if(res.delete(reservation)){
                JOptionPane.showMessageDialog(this, "réservation bien supprimée");
                afficherReservation();
            }
        }
    }//GEN-LAST:event_jButton3supprimerReservation

    private void jButton4imprimer(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4imprimer
       Document document = new Document();

        try {
            
            PdfWriter.getInstance(document, new FileOutputStream("recu.pdf"));

           
            document.open();
            Paragraph title = new Paragraph("liste des Réservations\n\n",FontFactory.getFont(FontFactory.HELVETICA_BOLD, 18, Font.BOLD));
            title.setAlignment(Paragraph.ALIGN_CENTER);
           
            document.add(title);
            document.add(new Paragraph("\n\n\n\n\n\n"));
 
                List<Reservation> reservations = res.findAll();
            
                for (Reservation reservation : reservations) {
                String nom = reservation.getClt().getNom();
                String prenom = reservation.getClt().getPrenom();
                String chambre = reservation.getCh().getCateg().getLibelle();
                String dateDebut = reservation.getDateDebut().toString();
                String dateFin = reservation.getDateFin().toString();

               
                document.add(new Paragraph("Client: " + nom + " " + prenom));
                document.add(new Paragraph("Chambre: " + chambre));
                document.add(new Paragraph("Date début: " + dateDebut));
                document.add(new Paragraph("Date fin: " + dateFin));
                document.add(new Paragraph("------------------------------------------------------------------------------------\n")); 
            }
            document.close();
            JOptionPane.showMessageDialog(this, "Reçu bien imprimé", "Succès", JOptionPane.INFORMATION_MESSAGE);

        } catch (FileNotFoundException ex) {
            Logger.log(Level.SEVERE, "File not found: recu.pdf", ex);
            JOptionPane.showMessageDialog(this, "Erreur: Fichier non trouvé", "Erreur", JOptionPane.ERROR_MESSAGE);

        } catch (DocumentException ex) {
            Logger.log(Level.SEVERE, "Error generating PDF document", ex);
            JOptionPane.showMessageDialog(this, "Erreur lors de la génération du PDF", "Erreur", JOptionPane.ERROR_MESSAGE);

        } finally {
            if (document.isOpen()) {
                document.close();
            }
        }
    }//GEN-LAST:event_jButton4imprimer

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
       Date dateDebut =jDateChooser1.getDate();
        Date dateFin=jDateChooser2.getDate();
        Client clt=(Client) jComboBox1.getSelectedItem();
        model.setRowCount(0);
        for(Reservation r:res.findAll()){
           if(r.getDateDebut().after(dateDebut) && r.getDateFin().before(dateFin)){
            model.addRow(new Object[]{
                r.getId(),
                r.getDateDebut(),
                r.getDateFin(),
                r.getCh().getCateg().getLibelle(),
                r.getClt().toString(),
                
            });
           }}
    }//GEN-LAST:event_jButton5ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JComboBox<Client> jComboBox1;
    private javax.swing.JComboBox<Chambre> jComboBox2;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private com.toedter.calendar.JDateChooser jDateChooser2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables

   
}
